#!/usr/bin/env bash

#
# backup - Backs up all important files that are important or not under revision control.
#
# SYNOPSIS
#   backup
#
# DESCRIPTION
#   Uses borg to backup a variety of important files.
#

set -euxo pipefail

borg create --stats --progress --exclude-from $HOME/.borg-exclude.lst ::archive-{hostname}-{now} \
    $HOME/.emacs.d \
    $HOME/.zsh* \
    $HOME/.aliases* \
    $HOME/.env_vars* \
    $HOME/.paths* \
    $HOME/.app-config* \
    $HOME/.config/cmus/* \
    $HOME/.config/rclone/* \
    $HOME/.hunspell_en_US \
    $HOME/.local/share/fonts/* \
    $HOME/Archive/Contacts \
    $HOME/Archive/Notes \
    $HOME/Projects \
    /etc/hosts \
    /etc/fstab
