#!/usr/bin/env bash

#
# backup-artist - Back up the given music artist directory to the cloud
#
# SYNOPSIS
#   backup-artist ARTIST-DIRECTORY
#
# DESCRIPTION
#   Copies the files in the given music artist directory to the Box and
#   Mega clouds using rclone. An incremental copy is done, so only
#   changed files are updated.
#
# EXAMPLES
#   backup-artist aliceeffekt
#   backup-artist "Cradle of Filth"
#

source "notification.sh"

REMOTES=(box mega)

artist_dir="${1}"

if [[ ! -d "${artist_dir}" ]]
then
  echo_error "Artist directory '${artist_dir}' does not exist"
  exit 1
fi

for remote in ${REMOTES[*]}
do
  echo_notify "Backing up to ${remote}..."
  rclone -P copy "${artist_dir}" "${remote}:Debajit/Music/${artist_dir}"
done
