#!/usr/bin/env bash

#
# backup-book-category - Backs up the category of books to the given remote.
#
# SYNOPSIS
#   backup-book-category <CATEGORY>
#
# DESCRIPTION
#   Copies the given Books sub-directory to the given cloud storages.
#
# NOTE
#   This script can be run from any directory.
#
# EXAMPLES
#    backup-book-category Thinking
#    backup-book-category Classics
#

source "notification.sh"

REMOTES=(box mega)
BOOKS_DIR="${HOME}/Documents/Books"

book_category="${1}"
book_category_dir="${BOOKS_DIR}/${book_category}"

if [[ ! -d "${book_category_dir}" ]]
then
  echo_error "Book category directory '${book_category_dir}' does not exist"
  exit 1
fi

for remote in ${REMOTES[*]}; do
  echo_notify "Backing up to '${book_category}' books to ${remote}..."
  rclone -P copy "${book_category_dir}" "${remote}:Debajit/Documents/Books/${book_category}"

  if [[ $? -eq 0 ]]; then
    echo_notify "Successfully backed up to ${remote}"
    # osascript -e 'display notification "✅ Uploaded changes" with title "Wiki Watcher" sound name "Submarine"'
    notify-send 'RClone' "Backed up '${book_category}' books to ${remote}"
  else
    echo_error "Failed to backup '${book_category}' books to ${remote}"
    notify-send 'RClone' "Failed to backup '${book_category}' books to ${remote}" --icon=dialog-error
  fi
done
