#!/usr/bin/env bash

#
# backup-artist - Back up the given music artist directory to the cloud
#
# SYNOPSIS
#   backup-artist ARTIST-DIRECTORY
#
# DESCRIPTION
#   Copies the files in the given music artist directory to the Box and
#   Mega clouds using rclone. An incremental copy is done, so only
#   changed files are updated.
#
# EXAMPLES
#   backup-artist aliceeffekt
#   backup-artist "Cradle of Filth"
#

source "backup.sh"
source "dir.sh"
source "notification.sh"

artist_dir="${1}"

for remote in tulip box mega
do
  backup_dir "${artist_dir}" "${remote}" "Debajit/Music/${artist_dir}"
done
