#!/usr/bin/env bash

#
# backup-receipts - Back up my receipts to several cloud stores
#
# SYNOPSIS
#   backup-receipts
#
# DESCRIPTION
#   Copies the files in ~/Documents/Receipts and stores them to
#   multiple cloud stores. An incremental copy is done, so only
#   changed files are updated.
#
# NOTE
#   This file can be run from any directory.
#

source "backup.sh"
source "dir.sh"
source "notification.sh"

for remote in tulip box mega
do
  backup_dir "${HOME}/Documents/Receipts" "${remote}" "Debajit/Documents/Receipts"
done
