#!/bin/sh

if [[ -d "${1}" ]]; then
  rclone -P copy "${1}" "box:Debajit/Music/${1}"
  rclone -P copy "${1}" "mega:Debajit/Music/${1}"
else
  echo "Artist directory '${1}' does not exist"
  exit 1
fi

