#!/usr/bin/env bash

#
# backup-book-category - Backs up the category of books to the cloud storage.
#
# SYNOPSIS
#   backup-book-category <CATEGORY>
#
# DESCRIPTION
#   Copies the given Books sub-directory to the given cloud storages.
#
# NOTE
#   This script can be run from any directory.
#
# EXAMPLES
#    backup-book-category Thinking
#    backup-book-category Classics
#

source "backup.sh"
source "dir.sh"
source "notification.sh"

for remote in tulip box mega
do
  backup_dir "${HOME}/Documents/Books/${1}" "${remote}" "Debajit/Documents/Books/${1}"
done
