#!/usr/bin/env bash

#
# borg-backup - Backs up important files that are generally not in git, git annex, or a BtrFS snapshot.
#
# SYNOPSIS
#   borg-backup
#
# DESCRIPTION
#   Uses borg to backup a variety of important files. These are mostly
#   user-files (with a few important system files for reference) that
#   are typically
#
#   - Not under revision control. This may include important
#     work-in-progress documents (like notes) that have not been
#     synced to the git upstream for instance.
#
#   - Not git-annexed
#
#   - Not backed up by the default BtrFS system snapshots (managed by
#     Timeshift for instance)
#

set -euxo pipefail

borg create -v --stats --progress --exclude-from $HOME/.borg-exclude.lst ::'archive-{hostname}-{now}' \
    $HOME/{.zsh*,.zprofile,.aliases*,.app-config*,.env_vars*,.paths*} \
    $HOME/{.emacs.d,.hunspell_en_US,.ssh/config} \
    $HOME/.config/{cmus,espanso,ranger,rclone}/* \
    $HOME/.config/BraveSoftware/Brave-Browser/Default/Bookmarks \
    $HOME/{.config,.local/share}/liferea \
    $HOME/.local/share/{Anki2,fonts,gthumb/catalogs}  \
    $HOME/Archive/Knowledge \
    $HOME/Pictures/Screenshots/ \
    $HOME/Projects \
    /boot \
    /etc/{fstab,hosts,mkinitcpio*,ssh/sshd_config} \
    /var/spool/cron/debajit
