#!/usr/bin/env bash

#
# git-pushall - Push all the uncommitted changes in the current git repo
#
# SYNOPSIS
#   git-pushall
#
# DESCRIPTION
#   Takes all the local uncommitted changes, adds them to a commit and
#   pushes them to the default git remote. The script needs to be run
#   from a git repo.
#

source "notification.sh"

# Check if there is anything to push
if [[ -z $(git status -s) ]]; then
  # Nothing to sync
  exit 0
fi

# The are local changes
echo_notify "Pushing..."

git add . && \
  git commit -m "Automatically synced using git-pushall" && \
  git push

if [[ $? -eq 0 ]]; then
  echo_notify "Successfully synced"
  send_notification 'Wiki Watcher' 'Uploaded changes'
else
  echo_error "Failed to sync"
  # TODO: Refactor into notification.sh
  notify-send 'Wiki Watcher' 'Failed to sync' --icon=dialog-error
fi
