#!/usr/bin/env bash

source "notification.sh"

if [[ -n $(git status -s) ]]; then
  echo_notify "Pushing..."

  git add . && \
    git commit -m "Automatically synced using git-pushall" && \
    git push

  if [[ $? -eq 0 ]]; then
    echo_notify "Successfully synced"
    # osascript -e 'display notification "✅ Uploaded changes" with title "Wiki Watcher" sound name "Submarine"'
    # TODO: Extract from param
    notify-send 'Wiki Watcher' 'Uploaded changes'
  else
    echo_error "Failed to sync"
    notify-send 'Wiki Watcher' 'Failed to sync' --icon=dialog-error
  fi
fi
