#!/usr/bin/env bash

if [[ -n $(git status -s) ]]; then
  echo "Pushing..."

  git add . && \
    git commit -m "Automatically synced using git-pushall" && \
    git push

  if [[ $? -eq 0 ]]; then
    echo "Successfully synced"
    osascript -e 'display notification "✅ Uploaded changes" with title "Wiki Watcher" sound name "Submarine"'
  else
    echo "Failed to sync"
  fi
fi


