#!/usr/bin/env bash

#
# mkv-set-title - Sets the title of an MKV video
#
# SYNOPSIS
#   mkv-set-title VIDEO_FILE_NAME [MOVIE_TITLE]
#
# DESCRIPTION
#   Sets the title property of an MKV video file.
#
# EXAMPLES
#   mkv-set-title file.mkv "My Movie name (1970)" # Sets the title to the given little string
#   mkv-set-title 'Solaris (1972).mkv'            # Sets the title to "Solaris (1972)"
#

set -euo pipefail

source "notification.sh"        # Provides echo_notify, echo_error

# Validate arguments
script_name="${0##*/}"
if [[ $# -eq 0 || $# -gt 2 || ! -f "$1" ]]; then
  echo_notify "${script_name} - Sets the title of an MKV video"
  echo "Usage: ${script_name} video_file [movie_title]"
  exit 1
fi

video_file="${1}"

video_title="${2:-}"
if [[ -z "${video_title}" ]]; then
  video_title="${video_file##*/}"   # Remove directory path
  video_title="${video_title%%.*}"  # Remove extension
fi

echo_notify "File:  '${video_file}'"
echo_notify "Title: '${video_title}'\n"

mkvpropedit "${video_file}" --edit info --set "title=${video_title}"
