#!/usr/bin/env bash

#
# mount-phone-music - Mounts the documents filesystem of the iPhone’s Flacbox app
#
# SYNOPSIS
#   mount-phone-music
#
# DESCRIPTION
#   Mounts the documents filesystem of the iPhone’s Flacbox app and
#   does a dry rsync run with the local music folder to indicate what
#   differences exist between the local machine and the phone. Having
#   the music documents filesystem mounted allows one to easily manage
#   one’s music on the phone using simple tools like rsync or a
#   script.
#

set -euo pipefail

source "notification.sh"        # Provides echo_notify, echo_error

MOUNTPOINT="${HOME}/Mounts/Flacbox"
MUSIC_SOURCE_DIR="${HOME}/Archive/Music"
MUSIC_DEST_DIR="${MOUNTPOINT}/Music"

mkdir -p "${MOUNTPOINT}" || die "Failed to create mountpoint “${MOUNTPOINT}”"

if mountpoint -q "${MOUNTPOINT}" || ifuse --documents "com.leshko.flap" "${MOUNTPOINT}"; then
  echo_notify "Mounted music app documents filesystem at “${MOUNTPOINT}”"
else
  die "Failed to mount music app documents filesystem at “${MOUNTPOINT}”"
fi

time rsync -avhsWL --progress --no-perms --no-owner --no-group --exclude-from ~/.rsync-exclude.lst "${MUSIC_SOURCE_DIR}/" "${MUSIC_DEST_DIR}/" --delete -ni
