#!/usr/bin/env bash

#
# notify - Sends a desktop notification, on the local machine, or to one or more remote hosts
#
# SYNOPSIS
#   notify MESSAGE
#   notify MESSAGE REMOTE_HOSTNAME
#   notify MESSAGE REMOTE_HOSTNAME1 REMOTE_HOSTNAME2 REMOTE_HOSTNAME3 ...
#
# DESCRIPTION
#   Displays a desktop notification, on the current machine, or on one
#   or more remote hosts. To send notifications to other machines,
#   ensure that you can SSH into that machine from the current
#   machine. The message to display the notification in such a case is
#   sent over SSH to the remote machine.
#
# EXAMPLES
#
#   notify "hello there"
#
#     Displays a desktop notification with the message "hello there",
#     and title set to the current hostname.
#
#   notify "hi there!" gnuarch gnumanjaro
#
#     Displays a desktop notification with the message "hi there!" on
#     the machines having the hostnames ‘gnuarch’ and ‘gnumanjaro’
#

set -euo pipefail

source "notification.sh"        # Provides echo_notify, echo_error

usage() {
  local script_name="${0##*/}"
  echo_notify "${script_name} - Sends a desktop notification, on the local machine, or to one or more remote hosts"
  echo "  Usage: "
  echo "    ${script_name} MESSAGE                          # Send a desktop notification on the local host"
  echo "    ${script_name} MESSAGE HOSTNAME                 # Send a desktop notification to another host"
  echo "    ${script_name} MESSAGE HOSTNAME1 HOSTNAME2 ...  # Send a desktop notification to multiple hosts"
  exit 1
}

(( $# == 0 )) && usage

message="${1}"
shift

# Send locally if no hostnames are given
(( $# == 0 )) && notify-send "$(hostname)" "${message}"

# Send to remote hosts otherwise
for host; do
  ssh "${host}" "notify-send '${host}' '${message}'"
done
