#!/usr/bin/env bash

#
# remux-to-mkv
#
# USAGE:
#   remux-to-mkv VIDEO_FILE_NAME
#
# DESCRIPTION:
#   Remuxes (i.e. converts losslessly) the given file into MKV format.
#   Among other things this allows you to package other files such as
#   a subtitles file or another audio track into the same MKV video
#   file.
#

set -euo pipefail

source "notification.sh"

# Check the number of arguments
script_name="${0##*/}"
if [[ $# -ne 1 || ! -f "$1" ]]; then
  echo_notify "${script_name} - Remuxes a video to MKV format"
  echo "Usage: ${script_name} video_file"
  exit 1
fi

input_file="$1"

# The %% removes the largest string segment towards the end that
# matches the pattern ".*" i.e it removes the file extension. See
# https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html#Shell-Parameter-Expansion
output_file="${input_file%%.*}.mkv"

if ffmpeg -i "${input_file}" -c copy -map 0 "${output_file}"; then
  echo_notify "Created '${output_file}'"
else
  echo_error "Failed to remux the file '${input_file}'"
fi
