#!/usr/bin/env bash

#
# run-app - Runs the application or a local server polymorphically depending on the directory
#
# SYNOPSIS
#   run-app
#
# DESCRIPTION
#   Depending on the directory where this script is run from, runs a
#   local server or the application. What is run is decided based on a
#   set of rules defined in this script.
#

set -euo pipefail

current_dir_name="${PWD##*/}"

if [[ -f "./config/_default/hugo.yaml" ]]; then
  gum spin --spinner points --title "Starting Hugo server..." -- xdg-open "http://localhost:1313" && hugo server -D --cleanDestinationDir
elif [[ -f "./package-lock.json" ]]; then
  npm start
else
  case "$current_dir_name" in
    dotfiles*) make;;
  esac
fi
