#!/usr/bin/env bash

#
# run-app - Runs the application or a local server polymorphically depending on the directory
#
# SYNOPSIS
#   run-app
#
# DESCRIPTION
#   Depending on the directory where this script is run from, runs a
#   local server or the application. What is run is decided based on a
#   set of rules defined in this script.
#

set -euo pipefail

source "notification.sh"        # Provides echo_notify, echo_error

show-progress() {
  message="${1}"
  gum spin --spinner points --title "${message}"
}

if [[ -f "./config/_default/hugo.yaml" ]]; then
  show-progress "Starting Hugo server..." -- xdg-open "http://localhost:1313" && hugo server -D --cleanDestinationDir --navigateToChanged
elif [[ -f "./package-lock.json" ]]; then
  show-progress "Starting npm server..." -- npm start
fi
