#!/usr/bin/env bash

#
# start-wiki - Start a TiddlyWiki server locally
#
# SYNOPSIS
#   start-wiki [PORT=4444]
#
# DESCRIPTION
#   Starts a TiddlyWiki server with the contents in ~/Documents/wiki.
#   Starts the server on 127.0.0.1 on port 4444 by default. Another port
#   can be specified by providing it as the first argument.
#
# EXAMPLES
#   start-wiki
#   start-wiki 5555
#

TIDDLYWIKI_LOCATION="${HOME}/Documents/wiki"
PORT=${1:-4444}

# See also https://unix.stackexchange.com/a/438357/141850
function echo_notify {
  echo -e "$(tput bold)$(tput setaf 154)➥ $(tput setaf 49)${1}$(tput sgr0)"
}

function echo_error {
  echo -e "$(tput bold)$(tput setaf 230)$(tput setab 196) ✘  Error $(tput sgr0) " \
       "$(tput bold)$(tput setaf 229)${1}$(tput sgr0)"
}

echo_notify "Starting TiddlyWiki server on port ${PORT}..."
tiddlywiki "${TIDDLYWIKI_LOCATION}" --server "${PORT}"
