#!/usr/bin/env bash

#
# sync-artist
#
# Syncs the artist directory from the local disk to the remote,
# deleting files from the remote if required.
#
# DEPENDENCIES:
# - bat for --dry-run option (for diff highlighting)
#

set -euo pipefail

source "notification.sh"

die() { echo_error "${1}" ; exit 1; }

dry_run=0
artist=""

while [[ -n "${1:-}" ]]; do
  case "${1}" in
    -n|--dry-run)
      dry_run=1
      ;;
    -*)
      echo_error "Invalid option '${1}'"
      exit 1
      ;;
    *)
      artist="${1%/}"
      ;;
  esac

  shift
done

[[ -d "${artist}" ]] || die "Artist directory '${artist}' does not exist"

if [[ $dry_run == 1 ]]; then
  echo_notify "Dry-syncing artist '${artist}'..."
  rclone check "${artist}" "box:Debajit/Music/${artist}" --combined - 2> /dev/null | grep -v '^=' | bat -p --language=diff
else
  echo_notify "Syncing artist '${artist}' to box"
  rclone -P sync "${artist}" "box:Debajit/Music/${artist}"
  echo_notify "Syncing artist '${artist}' to tulip"
  rclone -P sync "${artist}" "tulip:Debajit/Music/${artist}"
fi
