#!/usr/bin/env bash

source "notification.sh"
WIKI_ROOT="${HOME}/Documents/wiki"

echo_notify "Watching wiki at '${WIKI_ROOT}'.\n  " \
            "Changes will be uploaded upstream automatically."

watchexec -w "${WIKI_ROOT}" -d 3000 -i '$__StoryList.tid' -- git-pushall
