#!/usr/bin/env bash

source "notification.sh"

if [[ ! -d "tiddlers" ]]; then
  echo_error "This script needs to be run from inside a TiddlyWiki directory"
  exit 1
fi

echo_notify "Watching wiki. Changes will be uploaded upstream automatically."
watchexec -p -d 3000 -i '$__StoryList.tid' -- git-pushall
