#!/usr/bin/env bash

source "notification.sh"

echo_notify "Watching wiki in current directory. Changes will be uploaded upstream automatically."
watchexec -p -d 3000 -i '$__StoryList.tid' -- git-pushall
