#!/usr/bin/env bash

#
# write-playlists - Generates .m3u playlists from all cmus’ playlists
#
# SYNOPSIS
#   write-playlists
#
# DESCRIPTION
#   Takes all the cmus playlists and converts them into .m3u
#   playlists. Does this concurrently using CORES*2 processes.
#
# NOTES on performance
#
# - xargs takes 0.244s
# - GNU parallel takes 0.6s
#
# find "${HOME}/.config/cmus/playlists" -type f -print0 | parallel -0 -J "${process_count}" -N1 write-playlist
#

set -euo pipefail

process_count=$(($(nproc) * 2))

write-recent-playlist
find "${HOME}/.config/cmus/playlists" -type f -print0 | xargs -0 -P "${process_count}" -n1 write-playlist
